server.port=8080
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.ru.practicum.ewm=DEBUG