server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:6432/stats
spring.datasource.username=stats
spring.datasource.password=stats
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.ru.practicum.ewm=DEBUG
