CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        LONG    NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR NOT NULL,
    uri       VARCHAR NOT NULL,
    ip        VARCHAR NOT NULL,
    timestamp VARCHAR NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_endpoint_hit_app ON endpoint_hit (app);
CREATE INDEX IF NOT EXISTS idx_endpoint_hit_uri ON endpoint_hit (uri);
CREATE INDEX IF NOT EXISTS idx_endpoint_hit_timestamp ON endpoint_hit (timestamp);
CREATE INDEX IF NOT EXISTS idx_endpoint_hit_app_uri_timestamp ON endpoint_hit (app, uri, timestamp);